### ISSUE TITLE
` json_object_get_int` does not set `EINVAL` on invalid string

### ISSUE THREAD

**Issue by fedefrancescon** [json-c/json-c#792] opened 2022-10-24 15:21 UTC
**Describe the bug**
The doc states that `json_object_get_int` should set [ `errno` to `EINVAL`](https://json-c.github.io/json-c/json-c-0.16/doc/html/json__object_8h.html#a8c56dc58a02f92cd6789ba5dcb9fe7b1).
This is not the case! Looking at the code, in case the type is `string` and the parsing fails it returns `0` but `errno` is not set.

**Steps To Reproduce**
Compile the following code with no particular flags or settings:
```c
#include <assert.h>
#include <json-c/json.h>
#include <stdio.h>
#include <errno.h>

int main(const int argc, const char *argv[]){
  const char vals[][10] = {
    "b",
    "0xb",
    "0xB",
    "0xB0",
    "0B",
    "pippo",
    "pluto"
  };

  for (size_t i = 0; i < sizeof(vals)/sizeof(vals[0]); i++) {
    struct json_object *jtmp = json_object_new_string(vals[i]);
    errno = 0;
    int r = json_object_get_int(jtmp);
    printf("s: %-10s => i: %3lld errno: %d\n", vals[i], r, errno);
    json_object_put(jtmp);
  }

  return 0;
}
```
Will give you that output: 
```shell
s: b          => i:   0 errno: 0
s: 0xb        => i:   0 errno: 0
s: 0xB        => i:   0 errno: 0
s: 0xB0       => i:   0 errno: 0
s: 0B         => i:   0 errno: 0
s: pippo      => i:   0 errno: 0
s: pluto      => i:   0 errno: 0
```

**Version and Platform**
- json-c version: 777dd06be83ef7fac71c2218b565557cd068a714 , 0.15
- OS: Arch Linux x64 , Kirkstone on aarch64

**How to Proceed?**
I was on my way to issue a PR to fix this (with related test), it's a really easy fix. But I noticed that there is some inconsistency within:
* `json_object_get_double`
* `json_object_get_int`
* `json_object_get_int64`
 * `json_object_get_uint64`
 
`int` and `double` both state that invalid conversions should set `errno = EINVAL`, `double` actually seems to do this!
`int64` and `uint64` do not state the same and simply (at first glance) returns 0 in case of invalid parsing.

So, before going on an pushing a PR. Which way should I go? Which is the indended behaviour?
Could I go on and fix the missing `errno = EINVAL` or just remove the errno setting statement from the doc?

**Comment by hawicz** [comment] 2022-10-26 02:21
The fix for this belongs in the json_parse_int64() function.  That calls strtoll() with the expectation that it will set errno on failure, but the man page states that this is optional ("...may also set..."):

```
The implementation may also set errno to EINVAL in case no conversion was performed (no digits seen, and 0 returned).
```
so we'll need to set it explicitly to get consistent behavior.

**Comment by hawicz** [comment] 2022-10-26 02:24
Note that the `errno: 0` result for the cases that start with an actual "0" are the intended behavior.  In those, when the string is "coerced to a int" (as per the docs) the answer _is_ 0 and the extra characters are supposed to be ignored.

**Closed by hawicz** 2022-10-26 02:24 UTC
