### ISSUE TITLE
 json_tokener_parse_ex: `null` (4 bytes) only parses as valid JSON when passed with null terminator (5 bytes). Documentation issue?

### ISSUE THREAD

**Issue by dougvj** [json-c/json-c#681] opened 2020-11-14 00:45 UTC
Note: for general questions and comments, please use the forums at:
https://groups.google.com/forum/#!forum/json-c

**Describe the bug**

When using `json_tokener_parse_ex`

The parser does not correctly parse `null` (4 bytes), returning `json_tokener_continue`. To get `json_tokener_success`, It requires a null terminator, so `null\0` (5 bytes).

This is contrary to the documentation for the `str` parameter which states:

> This does not need to be null terminated.

I tested this with `true`, `false` with the same result. Strings parse correctly (such as `"hi"` 4 bytes) while numbers (ie `4.32` 4 bytes) also return continue, which is understandable in their case since they may in fact continue. 

Keeping this behavior and adding a point of clarification on this edge case in the documentation is suggested.

**Steps To Reproduce**
```c
#include <json-c/json.h>
#include <stdio.h>

int main() {
  json_tokener* tokener = json_tokener_new();
  json_tokener_parse_ex(tokener, "null", 4);
  enum json_tokener_error err = json_tokener_get_error(tokener);
  printf("Tokener State: %s\n", json_tokener_error_desc(err));
  json_tokener_free(tokener);
}
```

I expect `Tokener State: success` for output, instead I see `Tokener State: continue`

However, if I do:
```c
  json_tokener_parse_ex(tokener, "null", 5);
```

The parse succeeds. 

**Version and Platform**
- json-c version: [0.15-1]
- OS: [Arch Linux]

**Comment by hawicz** [comment] 2020-11-14 22:37
That's currently expected behavior, and it works that way for values that don't have a delimiter of some kind (i.e. closing quote, square brace or curly brace, for strings, arrays or objects respectively).
Strictly speaking, it _is_ true that you don't need a \0, you just need _something_ after the 'n', 'u', 'l', 'l' bytes.  The phrase in the docs saying that it doesn't need to be null terminated is referring to the fact that the length passed in is honored, not to any parsing result; perhaps that could be clarified somewhat.

Given that no matter what is after the valid value we're going to return success, I actually think it would make sense to change the behavior and return success earlier.

**Comment by ploxiln** [comment] 2020-11-14 22:56
fwiw the docs do include:

> If the caller knows that they are at the end of their input, the length passed MUST include the final '\0' character, so values with no inherent end (i.e. numbers) can be properly parsed, rather than just returning json_tokener_continue.

(which I suppose does not strictly need to be necessary for `true`, `false`, and `null`)

**Comment by dougvj** [comment] 2020-11-15 00:24
Nice I missed that. I realize just now I had been referring to v0.12 documentation which doesn't have that passage.

**Comment by hawicz** [comment] 2023-07-01 21:50
Working as intended, closing.

**Closed by hawicz** 2023-07-01 21:50 UTC
