### ISSUE TITLE
json_c_visit() not exported on Windows

### ISSUE THREAD

**Issue by mrsharkbait** [json-c/json-c#559] opened 2020-03-20 17:46 UTC
Is there a particular reason why this function is not exported, or was it an oversight?  The function is declared as int, not JSON_EXPORT.

Seems like the latter: https://github.com/json-c/json-c/issues/488

**Comment by hawicz** [comment] 2020-03-21 02:01
eh?  As you point out, it was an oversight, and has been fixed.  If the change from #488 (commit eae040a84) isn't working for some reason, feel free to re-open.

**Comment by dota17** [comment] 2020-03-23 03:25
When I was reproducing this problem，I found another question. I added the json-c library by using vcpkg and couldn't include the "json-c/json_visit.h" in VS.  So I can not use the parameter, such as JSON_C_VISIT_SECOND, JSON_C_VISIT_RETURN_CONTINUE and so on. Should we add the ```#include "json_visit.h"``` in json.h ？

**Comment by loch-cp** [comment] 2020-03-23 20:53
> Should we add the `#include "json_visit.h"` in json.h ？
Makes sense, since that would be consistent with the purpose of json.h.

**Comment by hawicz** [comment] 2020-03-25 02:09
No, please don't add any more headers to json.h, we should keep the namespace cleaner.
also, if you can't include json_visit.h in the first place then adding it to json.h will just break anyone that might already be using *that* header.

**Comment by hawicz** [comment] 2020-03-25 02:10
if there's some problem with the json_visit.h header then that should be fixed, but that's a separate issue

**Closed by hawicz** 2020-03-25 02:10 UTC

**Comment by dota17** [comment] 2020-03-25 02:17
agree,  I did not take this into account.
> also, if you can't include json_visit.h in the first place then adding it to json.h will just break anyone that might already be using that header.
