### ISSUE TITLE
cmake test fails with building json-c with icc

### ISSUE THREAD

**Issue by eladdidy** [json-c/json-c#721] opened 2021-08-22 09:42 UTC
I'm trying to build lib with intel compiler (ICC) and added the relevant CMAKE options for using the ICC .
Build is completed with some warnings but tests are failing

![image](https://user-images.githubusercontent.com/15775369/130350373-aea7e294-aee9-4b43-8b14-f5b63b073238.png)

**Comment by hawicz** [comment] 2021-08-22 16:13
Can you please take a look at the output in the tests/testSubDir/<nameoftest> directories and see what the actual failures were?

You can also try re-running it with ```VERBOSE=1 CTEST_OUTPUT_ON_FAILURE=1 make test```

**Comment by hawicz** [comment] 2022-07-30 19:59
We can't fix anything without details about what the problem is, closing.

**Closed by hawicz** 2022-07-30 19:59 UTC
