### ISSUE TITLE
if set __stdcall (/Gz)

### ISSUE THREAD

**Issue by kouzhudong** [json-c/json-c#723] opened 2021-09-29 01:18 UTC
2>arraylist.c
2>D:\git\my\fork\json-c\arraylist.c(171,62): error C2440: “函数”: 无法从“int (__stdcall *)(const void *,const void *)”转换为“_CoreCrtNonSecureSearchSortCompareFunction”
2>D:\git\my\fork\json-c\arraylist.c(171,56): warning C4024: “qsort”: 形参和实参 4 的类型不同
2>D:\git\my\fork\json-c\arraylist.c(177,76): error C2440: “函数”: 无法从“int (__stdcall *)(const void *,const void *)”转换为“_CoreCrtNonSecureSearchSortCompareFunction”
2>D:\git\my\fork\json-c\arraylist.c(177,70): warning C4024: “bsearch”: 形参和实参 5 的类型不同

Note: for general questions and comments, please use the forums at:
https://groups.google.com/forum/#!forum/json-c

**Describe the bug**
A clear and concise description of what the bug is, and any information about where you're running into the bug that you feel might be relevant.

**Steps To Reproduce**
List the steps to reproduce the behavior.
If possible, please attach a sample json file and/or a minimal code example.

**Version and Platform**
- json-c version: [e.g. json-c-0.14, or a specific commit hash]
- OS: [e.g. Ubuntu 20.04, Debian Buster, NetBSD 9, etc...]
- Custom cmake/build flags, if any

**Comment by kouzhudong** [comment] 2021-09-29 01:19
Debug Win32

**Comment by kouzhudong** [comment] 2021-09-29 01:23
error LNK2019: 无法解析的外部符号 _getenv@4，函数 __json_c_strerror@4 中引用了该符号

**Comment by hawicz** [comment] 2021-11-27 03:46
Appveyor builds are all working fine, even after updating the config to use up to VS2022 (https://ci.appveyor.com/project/hawicz/json-c/builds/41683818), so I'm closing this since I have no way of reproducing it nor enough detail in this issue to know what's going wrong.

**Closed by hawicz** 2021-11-27 03:46 UTC
