### ISSUE TITLE
Some subsequent call of lh_get_hash not working

### ISSUE THREAD

**Issue by robybeen** [json-c/json-c#594] opened 2020-05-05 16:45 UTC
![5u4](https://user-images.githubusercontent.com/26742821/81090917-bd7acb00-8efe-11ea-8f75-9a97cb25cd2a.PNG)

Hello,

using platform : Renesas Synergy S5D9 ( some Cortex M4)

I have succesfully integrated the framework and it is working absolutely just how it is supposed to when the device is running with the external debugger. But when I run the firmware in "release mode" ( no debugger/ same configuration) the devices crashes somewhere after calling lh_get_hash.
No watchdogs are being used, same configuration and everything for both use cases. Is there anything known about running the framework on embedded devices ? Some type of semi_hosting that doesn't exist when the device runs without debugger ? Does any workaround exist ? ( skipping the lh for example?) 

I don't really know what to look for if I had to debug the programm myself, I don't even have a proper way to debug it, since the only way I can follow some paths is by turning led's on and off :( .

Any advice will be greatfully apreciated !

Best regards

**Comment by hawicz** [comment] 2020-05-06 04:43
Perhaps your platform is picky about memory access that goes a bit beyond the actual end of the key?  The code in hashlittle() does that to try to eek out a bit more performance, but you can disable it by setting the VALGRIND env variable before running cmake, which will cause -DVALGRIND=1 to be included on the compile line, which will turn on more precise memory access when calculating the hash.

**Comment by robybeen** [comment] 2020-05-09 14:28
So i defined VALGRIND but it still doesn't work :( . Any other ideas ?

**Comment by hawicz** [comment] 2020-05-10 02:50
Without a debugger to figure out where exactly it's crashing this is going to be pretty tricky to figure out.  Maybe something changes about the memory layout when you use a debugger, e.g. the key ends up "accidentally" null terminated or something?
Anyway, if you can toggle some leds then I expect you'd be able to figure out more precisely how far it gets.  I'd suggest first try simply calling strlen(key) just before lh_get_hash(), and if that works then check for jso->o.c_object being invalid maybe by jso->o.c_object == char_hash_fn (though for that you'd need to make that variable non-static to linkhash.c).
The actual hash function called will be lh_char_hash(), which calls hashlittle() and it really doesn't do much beyond walking through the bytes of the key, but if both jso->o.c_object and key seem valid, then perhaps there's something about how it's do that that causes you probably, and knowing what exact line it's breaking should provide a bit more of a clue.

**Comment by MarcT512** [comment] 2020-05-10 13:16
Check the header file (json.h) and the library you're linking to (libjson-c.so) are not mismatched.

I ran into segfaults in my project when I accidentally included system provided header files from json-c-0.12 and linked with the library I built from git master. The solution was to add an include path to the git repository. 

I also added a runtime check to avoid future issues, similar to:

```
    if (json_c_version_num() != JSON_C_VERSION_NUM) {
        printf("Mismatched libjson-c header version %s, vs library version %s\n", JSON_C_VERSION, json_c_version());
        abort();
    }

```

**Comment by hawicz** [comment] 2020-05-13 02:55
Any luck getting this working?

**Comment by robybeen** [comment] 2020-05-13 11:33
@MarcT512 I am not using the library, I compile the Framework together with my application.

@hawicz not yet, I have a lot of stuff to do currently but as soon as I will find out some more info I will write it here

**Comment by hawicz** [comment] 2020-05-13 15:01
Ok.  One other thing that might help narrow down where the problem is would be to call lh_get_hash directly, early in your app, with some known good values.  e.g.:

    #include "json-c/linkhash.h"
    const char *somekey = "abcd1234";
    struct lh_table *t = lh_kchar_table_new(16, (lh_entry_free fn *)&free);
    unsigned long hash = lh_get_hash(t, somekey);

**Comment by robybeen** [comment] 2020-05-15 17:55
sorry, the github notification got far down my emails. Thanks alot for the tip, will definitely try that

**Comment by robybeen** [comment] 2020-05-23 14:07
@hawicz I tested with the code you gave to me (had to rewrite lh_get_hash to not be static and inline) and again, it works just fine with the debugger but crashes without.

**Comment by robybeen** [comment] 2020-05-23 16:08
![1](https://user-images.githubusercontent.com/26742821/82735161-e7662700-9d1f-11ea-88cf-fd1b7653fffb.PNG)

![2](https://user-images.githubusercontent.com/26742821/82735160-e634fa00-9d1f-11ea-8adb-748ea75c6df1.PNG)

Ok, I tracked down the problem a bit more and it might probably has something do to that time(NULL) doesn't work on embedded devices as I will have to write my own clock source. This is the only think I see that would make sense for now.

**Comment by hawicz** [comment] 2020-05-24 01:54
"time(NULL) doesn't work", as in _it_ crashes?  There's not particular reason to use time() there, you just need some kind of somewhat unpredictable value. 
If you want to confirm that (or rule that out), for testing it'd be perfectly fine to just hard code any value you want as the initial value of `random_seed` to skip the call to json_c_random_seed() entirely; since it's meant to be random, the rest of the code won't care what is there.

**Comment by robybeen** [comment] 2020-05-25 11:34
Ok. I added an internal clock counter to my get_time_seed() function and it now works just fine. You can close the issue if you want, or maybe add some flags or some extensions to customize this function.
Thank you very much for your help !

**Comment by hawicz** [comment] 2020-05-25 17:39
I'd love to merge in a fix for this problem, but I don't think I quite understand what was broken.  Is it that calling `time(NULL)` cause a crash?

Perhaps we can provide a convenient way to use some other hard to predict value.  Note that it doesn't need to be the time-of-day, it could be just about anything else that will vary each time the application starts up.
Can you please show the code that you used to get things working?

One thing that we probably _won't_ be able to do is reliably detect that `time(NULL)` is broken, at least not by trying to run a test program, since you're cross-compiling.
I tried poking around a bit in the (Renesas docs)[https://www.renesas.com/us/en/doc/products/renesas-synergy/apn/r12an0055eu0106-synergy-s7g2-s5d9-thermostat-getting-started.pdf], but the most I was able to figure out is that you're probably using GCC ARM v4.9.3, which by itself isn't really enough.  Is there a preprocessor define that indicates that you're building for a Renesas device, and specifically a S5D9?
If you can run `gcc -dM -E - </dev/null` or its equivalent it might provide some suggestions.

**Comment by robybeen** [comment] 2020-05-25 20:57
![rs_1](https://user-images.githubusercontent.com/26742821/82842194-e7f5ed80-9ed8-11ea-9762-257d45643dcf.PNG)
![rs_2](https://user-images.githubusercontent.com/26742821/82842196-e9271a80-9ed8-11ea-8647-89f3b190c1dd.PNG)
![rs_3](https://user-images.githubusercontent.com/26742821/82842198-ea584780-9ed8-11ea-943b-7d1e248d7302.PNG)

Sure I can provide the code, it is not much at all what I did here, I have a timer callback set up to trigger each 1 ms, and I just use the value of it in the multiplication. 

I know that declaring the function as an extern is not the way it should be done, but I didn't have the time to create some interesting design pattern with this. 

I indeed have gcc v4.9.3, the only symbol it's being defined is called :
![rs_4](https://user-images.githubusercontent.com/26742821/82842412-aca7ee80-9ed9-11ea-9511-07006145d625.PNG)

I think the problem will occur on multiple embedded devices because the operation of reading the current time requires SEMI_HOSTING , which is having a debugger connected to some kind of server that is able to provide input to some POSIX functions as fopen, scanf, .....

Some more high level programming language could provide an interface to this random seed, and from there on force the developer to implement a function with the given signature, in C we have to solve this on a bit more creative way.

Maybe you could just provide a standard implementation for this and otherwise trigger #error if the user doesn't provide some kind of clock source/ random value to the random seed.

**Comment by robybeen** [comment] 2020-05-25 21:04
![rs_5](https://user-images.githubusercontent.com/26742821/82842926-a6b30d00-9edb-11ea-9b3f-df05881c1f01.PNG)
I found a bit more specific define that is the exact name of the board, but keep in mind that S5D9 has multiple packages and also S1, S3 and S7 belong also to the "Synergy" family. But as mentioned before, I think the problem that occurs here isn't something specific for this processors.

**Comment by hawicz** [comment] 2020-07-22 02:29
Instead of trying to explicitly look for the S5D9 environments, I added a way to override what json_c_get_random_seed() calls.  e.g.:
cmake -DOVERRIDE_GET_RANDOM_SEED='do { extern uint32_t getMsTicks(void); int ms = getMsTicks() * 433494437; return ms; } while(0)' ..

**Closed by hawicz** 2020-07-22 02:29 UTC
