### ISSUE TITLE
json_object_from_fd(_ex) doesn't work with a socket descriptor

### ISSUE THREAD

**Issue by mnschipper** [json-c/json-c#876] opened 2024-10-31 11:43 UTC
**Description**
The json_object_from_fd(_ex) function does not work with a socket descriptor as a file descriptor. This is probably because the function reads from the file to the end of the file, while there is no end of file on the socket.

**Steps To Reproduce**
Create a socket sd. Connect the socket to an external peer. Wait with poll() until data is available on socket sd. Call json_object_from_fd( sd ). The function blocks.

**Version and Platform**
- json-c version: [json-c-0.16]
- OS: Debian Bookwurm

**Workaround**
```c
json_object *json_object_from_sd( int sd )
{
	enum json_tokener_error jErr;
	int nBytes;
	json_object *jsonObj = NULL;
	json_tokener *tok = json_tokener_new();
	do
	{
		char buffer[JSON_FILE_BUF_SIZE];
		nBytes = read( sd, buffer, sizeof(buffer) );
		if( nBytes > 0 )
		{
			jsonObj = json_tokener_parse_ex( tok, buffer, nBytes );
			jErr = json_tokener_get_error( tok );
		}
		else
			jErr = json_tokener_error_parse_eof;
	}
	while( jErr == json_tokener_continue );
	json_tokener_free( tok );
	return jsonObj;
}
```

**Comment by hawicz** [comment] 2024-11-01 02:56
Works fine for me.  Sounds like whatever you're connecting to isn't closing the (write side of its) connection.

Shell #1:
```
socat TCP-LISTEN:9981 EXEC:'echo {"foo": 123}'
```

Shell #2:
```
$ cat example.c
#include <stdio.h>
#include <stdlib.h>

#include "json_object.h"
#include "json_util.h"

#include <sys/types.h>
#include <sys/socket.h>
#include <netinet/in.h>
#include <arpa/inet.h>

int main(int argc, char **argv)
{
        int s = socket(AF_INET, SOCK_STREAM, 0);
        struct sockaddr_in dst;
        dst.sin_family = AF_INET;
        dst.sin_port = htons(9981);
        inet_aton("127.0.0.1", &dst.sin_addr);

        int ret = connect(s, (struct sockaddr *)&dst, sizeof(dst));
        printf("connect=%d\n", ret);

        json_object *o = json_object_from_fd(s);
        if (o)
                printf("%s\n", json_object_to_json_string(o));
        exit(0);
}
$ ./a.out
connect=0
{ "foo": 123 }
```

**Comment by mnschipper** [comment] 2024-11-04 07:43
Yes, that's my problem with json_object_from_fd(). I have a socket connection between 2 applications and they are sending JSON messages between each other but the socket is not closed. It looks like json_object_from_fd() is scanning until it reaches the end of the file.

**Comment by hawicz** [comment] 2024-11-09 04:30
There's not much else it can do, without either being hugely inefficient (reading a _single_ byte at a time until it gets to the end of a parseable json sequence) or reading too many bytes and then just throwing them away (since you can't seek backwards on a network fd).
json_object_from_fd was designed as a simple way to read a single json object from an already open file descriptor, and trying to do anything beyond that will require a somewhat more complicated API.

Note that your `json_object_from_sd` workaround fails in at least a couple of cases:
* if your socket is in non-blocking mode, then read() might return -1 with EAGAIN before you get a full json sequence read, leading to your func returning NULL early.  You need to check errno before deciding to bail out, and do your poll() or select() at the start of the loop so you don't just spin.
* if instead of a json object, array or string, the sender sends a series of digits, then stops, json_tokener_parse_ex will return json_tokener_continue (because the length passed doesn't include a terminating nul byte), and if your socket is blocking then it'll get stuck in the read() call.  This case also needs poll/select so you can have a timeout and do whatever is reasonable if that expires.

It also suffers from the same "read too much" problem that json_object_from_fd does.  It'll really only work if the sender sends exactly one json object (or perhaps a string, or an array), then stops long enough for the receiver to complete its read calls, and either the receiving socket is blocking or all the bytes arrive fast enough that read() never returns -1.

I currently have neither the time nor the desired to try to create an API that would cover all these cases, so I'm closing this and just declaring that json_object_from_fd isn't meant to work for sockets.

**Closed by hawicz** 2024-11-09 04:30 UTC
