### ISSUE TITLE
json_object_get_string free str memory

### ISSUE THREAD

**Issue by aleaksah** [json-c/json-c#636] opened 2020-06-23 01:28 UTC
String memory don't freed after refs count to zero.

**Steps To Reproduce**
```
    char answer[] = "{\"error\": {\"error_code\": 100,\"error_msg\": \"One of the parameters specified was missing or invalid: random_id is a required parameter\"}}";
    int anslen = strlen(answer);
    struct json_tokener *tok = json_tokener_new();
    struct json_object *json = json_tokener_parse_ex(tok, answer, anslen);
    struct json_object *error = json_object_object_get(json, "error");
    char *error_text;

    if(error)
    {
        struct json_object *error_m = json_object_object_get(error, "error_msg");
        error_text = json_object_get_string(error_m);
        printf(error_text);
    }
    json_object_put(json);

    json_tokener_free(tok);
    //error_text string still available, its memory not freed
```

**Version and Platform**
- json-c-0.14
- OS: Windows 10
- MSVC

**Comment by hawicz** [comment] 2020-06-23 02:50
Works fine for me.  I ran your exact code through valgrind, and it reported no leaks, and I stepped through the json_object_put(json) call and confirmed that free() _is_ being called on the memory allocated for that string.  However, I'm not doing this on a Windows system, so perhaps things are different somehow.

How did you check that the memory is not freed?

**Comment by aleaksah** [comment] 2020-06-23 08:26
Windows free() in debug mode replaced by _free_dbg, that fills freed memory with 0xDD pattern. But after code I placed in first post - error_text string still available in memory.

**Comment by hawicz** [comment] 2020-06-25 04:19
Closing, since I believe it's working fine.

**Closed by hawicz** 2020-06-25 04:19 UTC
