### ISSUE TITLE
configure fails: checking size of size_t... configure: error: cannot determine a size for size_t

### ISSUE THREAD

**Issue by eyalsol** [json-c/json-c#229] opened 2016-05-23 05:34 UTC
building fresh copy of json-c from github fails with the above error. to reproduce:

1.  git clone git@github.com:json-c/json-c.git

2.   cd json-c

3.  ./autogen.sh

4.  configure

.
.
.
checking whether C compiler accepts -D_GNU_SOURCE... yes
checking whether C compiler accepts -D_REENTRANT... yes
checking size of int... 4
checking size of long... 8
checking size of size_t... configure: error: cannot determine a size for size_t

**Comment by ebassi** [comment] 2016-05-23 09:17
This is likely caused by a `builddir != srcdir` issue; the compiler cannot find `json_inttypes.h` in the inclusion path.

Even if it could find it, the `JSON_C_HAVE_INTTYPES_H` symbol would not be defined at configuration time (as it would only be defined inside `config.h` at the end of the process) which means that `json_inttypes.h` would just be reduced to `stdint.h`.

Thus, the appropriate way to check for `size_t` is:

```
AX_COMPILE_CHECK_SIZEOF(size_t, [#include <stdint.h>])
```

**Comment by ebassi** [comment] 2016-05-23 09:25
Opened PR #230 with the fix.

**Comment by hawicz** [comment] 2016-06-07 03:10
Should be fixed by the change in #230

**Closed by hawicz** 2016-06-07 03:10 UTC
