### ISSUE TITLE
Error while compiling source from RHEL5, could you please help me to fix this 

### ISSUE THREAD

**Issue by LINSEEcreate** [json-c/json-c#244] opened 2016-07-28 11:48 UTC
extrated from `make check` output
testReplaceExisting.c
testReplaceExisting.c: In function ‘main’:
testReplaceExisting.c:57:2: error: variable ‘val2’ set but not used [-Werror=unused-but-set-variable]
testReplaceExisting.c:42:2: error: variable ‘val’ set but not used [-Werror=unused-but-set-variable]
testReplaceExisting.c:25:2: error: variable ‘val0’ set but not used [-Werror=unused-but-set-variable]
cc1: all warnings being treated as errors
make[2]: *** [testReplaceExisting.o] Error 1
make[2]: Leaving directory `/tmp/json-c-0.12.1/tests'
make[1]: *** [check-am] Error 2
make[1]: Leaving directory `/tmp/json-c-0.12.1/tests'
make: *** [check-recursive] Error 1 

# cat Makefile.am.inc

AM_CFLAGS = -Wall -Werror -Wno-error=deprecated-declarations -Wextra -Wwrite-strings -Wno-unused-parameter -std=gnu99 -D_GNU_SOURCE -D_REENTRANT 

we are using for compile 

autoconf version 2.69 
gcc 4.7.3

**Comment by hawicz** [comment] 2016-07-28 15:38
Duplicate of issue #240

**Closed by hawicz** 2016-07-28 15:38 UTC
